version: "3.7"
services:
  postgres:
    container_name: postgres-for-unittest
    image: postgres:11.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "5490:5432"